#!/usr/bin/env python

#  Copyright (c) 2010, Philip Busch <philip@0xe3.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   - Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#   - Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.


import gtk
import gobject
from Xlib import X, display, error, Xatom, Xutil
import Xlib.protocol.event


# number of pixels between outer border and the actual grid
padding = 2

# number of pixels between grid boxes
spacing = 1

# foreground color (inactive desktops)
color_normal = '#333333'

# highlight color (the active desktop)
color_highlight = '#999999'

# background color ("transparent" for transparent background)
color_background = 'transparent'

# number of rows in desktop grid
rows = 2

# number of columns in desktop grid
cols = 3


class nap:
	def __init__(self):
		'''Initialization.'''
		# program info
		self.name = "neap"
		self.version = "0.2"
		self.author = ["Philip Busch <philip@0xe3.com>"]
		self.website = "http://code.google.com/p/neap/"

		# default config
		self.padding = 3
		self.spacing = 1
		self.color_normal = "green"
		self.color_highlight = "red"
		self.color_background = "yellow"
		self.rows = 2
		self.cols = 3
		self.grid = []

		# menus
		self.menu_about = None

		self.display = display.Display()
		self.screen  = self.display.screen()
		self.root    = self.screen.root 

		self.desktop = self.get_desktop_names()

		self.pixbuf = gtk.gdk.Pixbuf(gtk.gdk.COLORSPACE_RGB, True, 8, 20, 20)
		self.pixbuf.fill(0xffffffff)

		self.icon = gtk.StatusIcon()
		self.icon.set_from_pixbuf(self.pixbuf)
		self.update_pixbuf(self.get_current_desktop())

		self.icon.connect("activate", self.left)
		self.icon.connect("popup-menu", self.right)

		self.get_desktop_tasks(0)


	def get_desktop_tasks(self, num):
		'''Returns a list of tasks for desktop num.'''
		return self.root.get_full_property(self.display.intern_atom("_NET_CLIENT_LIST"), Xatom.WINDOW).value

	def get_current_desktop(self):
		'''Returns the index of the currently active desktop.'''
		return self.root.get_full_property(self.display.intern_atom("_NET_CURRENT_DESKTOP"), 0).value[0]

	def get_desktop_count(self):
		'''Returns the current number of desktops.'''
		return self.root.get_full_property(self.display.intern_atom("_NET_NUMBER_OF_DESKTOPS"), 0).value[0]

	def get_desktop_names(self):
		'''Returns a list containing desktop names.'''
		count = self.get_desktop_count()
		names = self.root.get_full_property(self.display.intern_atom("_NET_DESKTOP_NAMES"), 0)  
		if hasattr(names, "value"):
			names = names.value.strip("\x00").split("\x00")
		else:
			names = []
			for i in range(count):
				names.append(str(i)) 

		if len(names) < count:
			for i in range(len(names), count):
				names.append(str(i))  

		return names


	def update_grid(self):
		'''Updates internal grid structure.'''
		w, h = self.pixbuf.get_width(), self.pixbuf.get_height()

		n = max(self.rows, self.cols)
		c = (w - 2 * self.padding - (n - 1) * self.spacing) / self.cols

		grid_width = self.cols * c + (self.cols - 1) * self.spacing
		grid_height = self.rows * c + (self.rows - 1) * self.spacing

		off_x = (w - 2*self.padding - grid_width) / 2
		off_y = (h - 2*self.padding - grid_height) / 2

		grid = []
		for i in range(self.rows):
			for j in range(self.cols):
				x = off_x + self.padding + j*(c + self.spacing)
				y = off_y + self.padding + i*(c + self.spacing)

				if i * self.rows + j < len(self.desktop) - 1:
					grid.append((x, y, c, c))

		self.grid = grid

	def update_pixbuf(self, active = -1):
		'''Updates internal icon pixbuf.'''
		self.update_grid()
		w, h = self.pixbuf.get_width(), self.pixbuf.get_height()

		map = gtk.gdk.Colormap(gtk.gdk.visual_get_best(), False)
		color_normal = map.alloc_color(self.color_normal)
		color_high   = map.alloc_color(self.color_highlight)
		color_back   = map.alloc_color(self.color_background)

		pixmap = gtk.gdk.Pixmap(None, w, h, 32)
		gc = pixmap.new_gc()

		#---ACTUAL DRAWING CODE---
		gc.set_foreground(color_back)
		pixmap.draw_rectangle(gc, True, 0, 0, w, h)

		gc.set_foreground(color_normal)

		i = 0
		for cell in self.grid:
			if(i == active):
				gc.set_foreground(color_high)
			else:
				gc.set_foreground(color_normal)

			i = i + 1

			x, y, size_x, size_y = cell
			pixmap.draw_rectangle(gc, True, x, y, size_x, size_y)
		#-------------------------

		self.pixbuf.get_from_drawable(pixmap, map, 0, 0, 0, 0, w, h)
		self.pixbuf = self.pixbuf.add_alpha(True, 0x23, 0x57, 0xbd)
		self.icon.set_from_pixbuf(self.pixbuf)


	def get_screen(self):
		'''Returns the clicked grid box number.'''
		pointer_x, pointer_y, mods = self.icon.get_screen().get_root_window().get_pointer()

		screen, rectangle, orientation = self.icon.get_geometry()
		width, height, size_x, size_y = rectangle;

		pos_x = pointer_x - width
		pos_y = pointer_y - height

		i = 0
		for cell in self.grid:
			x, y, size_x, size_y = cell
			if pos_x >= x and pos_x <= x + size_x and pos_y >= y and pos_y <= y + size_y:
				return i
			i = i + 1

		return -1


	def left(self, status_icon):
		'''Callback for left-clicks.'''
		num = self.get_screen()

		if 0 <= num <= len(self.desktop):
			self.update_pixbuf(num)
			gobject.idle_add(self.switch_desktop, num)


	def switch_desktop(self, num):
		'''Sets the active desktop to num.'''
		win = self.root
		ctype = self.display.intern_atom("_NET_CURRENT_DESKTOP")
		data = [num]

		self.send_event(win, ctype, data)
		self.display.flush()


	def send_event(self, win, ctype, data, mask=None):
		'''Sends a ClientMessage event to the root window.'''
		data = (data+[0]*(5-len(data)))[:5]
		ev = Xlib.protocol.event.ClientMessage(window=win, client_type=ctype, data=(32,(data)))

		if not mask:
			mask = (X.SubstructureRedirectMask|X.SubstructureNotifyMask)
		self.root.send_event(ev, event_mask=mask)


	def desktop_callback(self, widget, data=None):
		'''Callback for the menu's desktop selector.'''
		if widget.get_active():
			self.switch_desktop(data)

	def get_menu_about(self):
		'''Returns a menu for the right-click action.'''
		menu = gtk.Menu()

		submenu = gtk.Menu()
		group = None
		i = 0
		for desktop in self.get_desktop_names():
			item = gtk.RadioMenuItem(group, desktop)

			if group == None:
				item.set_active(True)

			group = item
			item.connect("toggled", self.desktop_callback, i)
			i = i+1
			submenu.add(item)

		item = gtk.MenuItem("Desktops")
		item.set_submenu(submenu)
		menu.add(item)


		sep = gtk.SeparatorMenuItem()
		menu.add(sep)

		item = gtk.ImageMenuItem(gtk.STOCK_ABOUT)
		item.connect("activate", self.about)
		menu.add(item)

		#item = gtk.ImageMenuItem(gtk.STOCK_QUIT)
		#item.connect("activate", gtk.main_quit)
		#menu.add(item)

		self.menu = menu
		menu.show_all()
		return menu



	def right(self, status_icon, button, activate_time):
		'''Callback for right-clicks.'''
		if self.menu_about == None:
			self.menu_about = self.get_menu_about()

		self.menu_about.popup(None, None, gtk.status_icon_position_menu, 1, activate_time, self.icon)


	def about(self, menu_item):
		'''Shows an about dialog.'''
		about = gtk.AboutDialog()

		about.set_name(self.name)
		about.set_version(self.version)
		about.set_authors(self.author)
		about.set_comments("notification area / systray pager")
		about.set_copyright("Copyright (c) 2010 Philip Busch")
		about.set_website(self.website)
		about.set_logo(self.pixbuf)
		about.set_program_name(self.name)
		about.run()
		about.hide()


	def set_padding(self, padding):
		self.padding = padding

	def set_spacing(self, spacing):
		self.spacing = spacing

	def set_color_normal(self, color):
		self.color_normal = color

	def set_color_highlight(self, color):
		self.color_highlight = color

	def set_color_background(self, color):
		if color == "transparent":
			color = '#2357bd'

		self.color_background = color

	def set_rows(self, rows):
		self.rows = rows

	def set_cols(self, cols):
		self.cols = cols

	def main(self):
		num = self.get_current_desktop()
		self.update_pixbuf(num)
		gtk.main()


if __name__ == '__main__':
	nap = nap()

	nap.set_padding(padding)
	nap.set_spacing(spacing)
	nap.set_color_normal(color_normal)
	nap.set_color_highlight(color_highlight)
	nap.set_color_background(color_background)
	nap.set_rows(rows)
	nap.set_cols(cols)

	nap.main()



